### ISSUE TITLE
qx serve or qx compile --watch failes with ENOSPC nodejs error

### ISSUE THREAD

**Issue by pcrespov** [qooxdoo/qooxdoo-compiler#195]
```
Running 'qx compile --watch' ...
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: watch /home/scu/qooxdoo-sdk/framework/source/resource/qx/icon/Oxygen/48/actions/application-exit.png ENOSPC
    at _errnoException (util.js:1024:11)
    at FSWatcher.start (fs.js:1374:19)
    at Object.fs.watch (fs.js:1400:11)
    at createFsWatchInstance (/home/scu/node_modules/chokidar/lib/nodefs-handler.js:37:15)
    at setFsWatchListener (/home/scu/node_modules/chokidar/lib/nodefs-handler.js:80:15)
    at FSWatcher.NodeFsHandler._watchWithNodeFs (/home/scu/node_modules/chokidar/lib/nodefs-handler.js:228:14)
    at FSWatcher.NodeFsHandler._handleFile (/home/scu/node_modules/chokidar/lib/nodefs-handler.js:255:21)
    at FSWatcher.<anonymous> (/home/scu/node_modules/chokidar/lib/nodefs-handler.js:473:21)
    at FSReqWrap.oncomplete (fs.js:153:5)
'
```
**Configuration**
Description:	Ubuntu 18.04 LTS
Release:	18.04
Codename:	bionic

node v8.11.3
npm 6.1.0

qooxdoo-compiler: v0.2.13
qooxdoo-sdk : 6.0.0-alpha

**Workaround**
Seems to be related with the fact that the limits of files to watch reached a limit and **not** the lack of disk space. [Here](https://github.com/guard/listen/wiki/Increasing-the-amount-of-inotify-watchers) and explanation of technical details. This command set a new limit and made it permanent:
```bash
echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
```

I wonder if there is a way to handle this better so it does not require increasing the max_user_watches or at least produce a error message that would point you to the actual issue.

**Comment by cboulanger** [comment]
@johnspackman How should this be handled?

**Comment by johnspackman** [comment]
@pcrespov is correct - the user has to enter the command to increase `fs.inotify.max_user_watches` above it's paltry default.  I'll trap the message and give a proper warning
