### ISSUE TITLE
"sudo npm install -g qxcompiler" hangs on macOS

### ISSUE THREAD

**Issue by dgtlrift** [qooxdoo/qooxdoo-compiler#254]
NPM hangs attempting to install qxcompiler. I always get a few git errors, then it hangs on "extract binary-extensions@1.11.0"

```
MacBook Pro Computer:~ jim$ sudo npm install -g qxcompiler
Unhandled rejection Error: Command failed: /usr/local/bin/git clone --depth=1 -q -b master git://github.com/pgaubatz/es6-promisify.git /Users/jim/.npm/_cacache/tmp/git-clone-8d8a509f
/Users/jim/.npm/_cacache/tmp/git-clone-8d8a509f/.git: Permission denied

    at ChildProcess.exithandler (child_process.js:294:12)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:962:16)
    at Socket.stream.socket.on (internal/child_process.js:381:11)
    at Socket.emit (events.js:182:13)
    at Pipe._handle.close (net.js:610:12)

Unhandled rejection Error: Command failed: /usr/local/bin/git clone --depth=1 -q -b editable-json https://github.com/johnspackman/json-to-ast.git /Users/jim/.npm/_cacache/tmp/git-clone-72fad80a
/Users/jim/.npm/_cacache/tmp/git-clone-72fad80a/.git: Permission denied

    at ChildProcess.exithandler (child_process.js:294:12)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:962:16)
    at Socket.stream.socket.on (internal/child_process.js:381:11)
    at Socket.emit (events.js:182:13)
    at Pipe._handle.close (net.js:610:12)

⸨            ░░░░░░⸩ ⠹ extract:qooxdoo-sdk: sill extract binary-extensions@1.11.0
^C
MacBook Pro Computer:~ jim$ uname -a
Darwin MacBook Pro Computer 15.6.0 Darwin Kernel Version 15.6.0: Thu Jun 21 20:07:40 PDT 2018; root:xnu-3248.73.11~1/RELEASE_X86_64 x86_64
MacBook Pro Computer:~ jim$ 
```

This may be more of an issue with NPM but other installs have no issue, and may be related to the git errors.

**Comment by cboulanger** [comment]
Can you try installing without "sudo" ? https://medium.com/@ExplosionPills/dont-use-sudo-with-npm-still-66e609f5f92

**Comment by oetiker** [comment]
I use qx-compiler happily on my mac ... 

* setup nvm https://github.com/creationix/nvm
* and consider NOT installing qx-compiler with -g ... keep it together with your project.

**Comment by cboulanger** [comment]
@dgtlrift Do you still have this problem or can the issue be closed?

**Comment by cboulanger** [comment]
No feedback within more than a month, closing.
