### ISSUE TITLE
requirements

### ISSUE THREAD

**Issue by oetiker** [qooxdoo/qooxdoo-compiler#328]
I have been trying to add requirements to my contrib https://github.com/ITISFoundation/qx-osparc-theme now when I try to compile it, without the requirement installed the compiler just fails with a terrible error message

```
oetiker>./node_modules/.bin/qx compile
(node:13040) ExperimentalWarning: The fs.promises API is experimental
Error: TypeError: Cannot read property 'ITISFoundation/qx-iconfont-material' of undefined
    at libs.find.entry (/scratch/oetiker/qx-osparc-theme_node/qxcompiler/lib/qx/tool/cli/commands/Compile.js:631:74)
    at Array.find (<anonymous>)
    at libs.forEach.lib (/scratch/oetiker/qx-osparc-theme_node/qxcompiler/lib/qx/tool/cli/commands/Compile.js:631:30)
    at Array.forEach (<anonymous>)
    at defaultConstructor.__checkDependencies (/scratch/oetiker/qx-osparc-theme_node/qxcompiler/lib/qx/tool/cli/commands/Compile.js:597:12)
```

I have since found that if I have previously installed the required library and it is listed in the contrib.json file then it does get installed automatically on first compile ... not sure if this extends to applications using my contrib though ...

**Comment by johnspackman** [comment]
Fixed in https://github.com/qooxdoo/qooxdoo-compiler/pull/329
