### ISSUE TITLE
Error in property updatePoFiles of class qx.tool.compiler.targets.SourceTarget

### ISSUE THREAD

**Issue by cboulanger** [qooxdoo/qooxdoo-compiler#387]
@zaucker  reports:
```
qx serve
Error: Error in property updatePoFiles of class qx.tool.compiler.targets.SourceTarget in method $$setUpdatePoFilesImpl with incoming value 'undefined': Undefined value is not allowed!
    at Object.error (/Users/zaucker/checkouts/easii/frontend/node_modules/qxcompiler/node_modules/qooxdoo/qx-oo.js:8299:13)
    at defaultConstructor.set (eval at __installFunctionFromCode (/Users/zaucker/checkouts/easii/frontend/node_modules/qxcompiler/node_modules/qooxdoo/qx-oo.js:8361:35), <anonymous>:3:110)
    at defaultConstructor.eval [as $$setUpdatePoFilesImpl] (eval at __installFunctionFromCode (/Users/zaucker/checkouts/easii/frontend/node_modules/qxcompiler/node_modules/qooxdoo/qx-oo.js:8361:35), <anonymous>:3:524)
    at defaultConstructor.eval [as setUpdatePoFiles] (eval at __installFunctionFromCode (/Users/zaucker/checkouts/easii/frontend/node_modules/qxcompiler/node_modules/qooxdoo/qx-oo.js:8361:35), <anonymous>:3:29)
    at defaultConstructor.eval (eval at __attachPropertyMethods (/Users/zaucker/checkouts/easii/frontend/node_modules/qxcompiler/node_modules/qooxdoo/qx-oo.js:8156:26), <anonymous>:3:108)
    at defaultConstructor.createMakerFromConfig (/Users/zaucker/checkouts/easii/frontend/node_modules/qxcompiler/lib/qx/tool/cli/commands/Compile.js:431:14)
    at defaultConstructor.process (/Users/zaucker/checkouts/easii/frontend/node_modules/qxcompiler/lib/qx/tool/cli/commands/Compile.js:298:45)
```

**Comment by paragasu** [comment]
I am facing this problem. Is there any workaround for this?

**Comment by paragasu** [comment]
The workaround i use currently is just to use `qx compile --watch` and use nginx server to serve the page. I just have to put the nginx's root configuration to source-output directory and i can continue working on the code. Hope it helps.
