### ISSUE TITLE
Timining issue/Babel bug on build target

### ISSUE THREAD

**Issue by cboulanger** [qooxdoo/qooxdoo-compiler#541]
The problem can be seen on Travis
See https://travis-ci.org/cboulanger/eventrecorder/builds/571695701

When I run it locally, I get

```
Minifying widgetbrowser_recorder part-0.js
Parse error in output file part-0.js, line 100429 column 150: Unexpected token keyword «function», expected punc «:»
```
part-0.js, line 100429 is ("===>")

```
      /**
       * Start automatically displaying the tooltips
       * @ignore(HTMLElement)
       */
      init: function init() {
        var _this = this;

        var tooltip = new qx.ui.tooltip.ToolTip();
        this.addGlobalEventListener(function (target, event) {
          if (target === tooltip.getContentElement().getDomElement()) {
            return;
          }

          var type = event.getType();

===>         var id = typeof target.getAttribute == "function" ? target.getAttribute("data-qx-object-id") || target.toString() + " (no qx id attribute)" function asyncGeneratorStep(gen, resolve, reject, _next, _throw, key, arg) { try { var info = gen[key](arg); var value = info.value; } catch (error) { reject(error); return; } if (info.done) { resolve(value); } else { Promise.resolve(value).then(_next, _throw); } }
```

This is with the current event recorder master (https://github.com/cboulanger/eventrecorder)

**Comment by cboulanger** [comment]
The original code is here: https://github.com/cboulanger/eventrecorder/blob/master/source/class/cboulanger/eventrecorder/ObjectIdTooltip.js#L30

**Comment by cboulanger** [comment]
Since I'l be replacing the ternary expression with if statements, here's the link to the original:
https://github.com/cboulanger/eventrecorder/blob/590c7fadc895745c3684552de943ce70fdba2f75/source/class/cboulanger/eventrecorder/ObjectIdTooltip.js#L37

**Comment by cboulanger** [comment]
After replacing the ternary expression, I get this:
```
Error: Error: ENOENT: no such file or directory, rename 'compiled/build/widgetbrowser_recorder/part-0-tmp.js' -> 'compiled/build/widgetbrowser_recorder/part-0.js'
    at Function.__callStaticMethod (/Users/cboulanger/.nvm/versions/node/v8.13.0/lib/node_modules/@qooxdoo/compiler/node_modules/@qooxdoo/framework/lib/qx_server/part-0.js:27631:66)
    at Function.all (/Users/cboulanger/.nvm/versions/node/v8.13.0/lib/node_modules/@qooxdoo/compiler/node_modules/@qooxdoo/framework/lib/qx_server/part-0.js:27216:27)
    at Object.eachOf (/Users/cboulanger/.nvm/versions/node/v8.13.0/lib/node_modules/@qooxdoo/compiler/source/class/qx/tool/utils/Promisify.js:179:25)
    at defaultConstructor._writeBootJs (/Users/cboulanger/.nvm/versions/node/v8.13.0/lib/node_modules/@qooxdoo/compiler/source/class/qx/tool/compiler/targets/BuildTarget.js:141:46)
    at writeBootJs (/Users/cboulanger/.nvm/versions/node/v8.13.0/lib/node_modules/@qooxdoo/compiler/source/class/qx/tool/compiler/targets/Target.js:798:17)
    at <anonymous>
```

**Comment by johnspackman** [comment]
I think that this was caused by multiple applications with the same name, causing the compiler to rewrite the output file.  

https://github.com/qooxdoo/qooxdoo-compiler/issues/542
