### ISSUE TITLE
compile.js do not work with deploy

### ISSUE THREAD

**Issue by hkollmann** [qooxdoo/qooxdoo-compiler#694]
Problem is here
```
      let cmd = new qx.tool.cli.commands.Compile(compileArgv);
      await cmd.process();
```

The events of cmd are not captured and refired in deploy. 
Second problem is
```
      if (command instanceof qx.tool.cli.commands.Compile) {
        command.addListener("writtenApplication", (e) => this.__appCompiling(e.getData()));
      }
```
used in compile.js.

Would it be possible to extend Deploy from Compile instead of Command?

Then this is working out of the box.

**Comment by cboulanger** [comment]
Inheriting from compile would also solve the problem that the `--config-file` argument would be parsed and used. As far as I can see in https://github.com/qooxdoo/qooxdoo-compiler/blob/master/source/class/qx/tool/cli/commands/Deploy.js , there is nothing to suggest that it would - `compileArgv` does not contain a `configFile` property.

**Comment by hkollmann** [comment]
That would solve the problem that qx deploy is not working any longer with the new compiler:

```
Error: Error: Error in property libraryPoPolicy of class qx.tool.compiler.targets.BuildTarget in method $$setLibraryPoPolicyImpl with incoming value 'undefined': Undefined value is not allowed!
    at Object.qx.core.Property.error() [as error] (C:\_vza\@repos\github.windows\qooxdoo\qooxdoo-compiler\node_modules\@qooxdoo\framework\lib\qx_server\boot.js:13176:15)
    at wrapper.set (eval at __installFunctionFromCode (C:\_vza\@repos\github.windows\qooxdoo\qooxdoo-compiler\node_modules\@qooxdoo\framework\lib\qx_server\boot.js:13217:36), <anonymous>:3:110)
    at wrapper.qx.tool.compiler.targets.Target.prototype.$$setLibraryPoPolicyImpl() [as $$setLibraryPoPolicyImpl] (eval at __installFunctionFromCode (C:\_vza\@repos\github.windows\qooxdoo\qooxdoo-compiler\node_modules\@qooxdoo\framework\lib\qx_server\boot.js:13217:36), <anonymous>:3:540)
    at wrapper.qx.tool.compiler.targets.Target.prototype.setLibraryPoPolicy() [as setLibraryPoPolicy] (eval at __installFunctionFromCode (C:\_vza\@repos\github.windows\qooxdoo\qooxdoo-compiler\node_modules\@qooxdoo\framework\lib\qx_server\boot.js:13217:36), <anonymous>:3:31)
    at wrapper.eval (eval at __attachPropertyMethods (C:\_vza\@repos\github.windows\qooxdoo\qooxdoo-compiler\node_modules\@qooxdoo\framework\lib\qx_server\boot.js:13065:28), <anonymous>:3:114)
    at C:\_vza\@repos\github.windows\qooxdoo\qooxdoo-compiler\source\class\qx\tool\cli\commands\Compile.js:675:16
    at Array.qx.lang.normalize.Array.forEach() [as forEach] (C:\_vza\@repos\github.windows\qooxdoo\qooxdoo-compiler\node_modules\@qooxdoo\framework\lib\qx_server\boot.js:10169:22)
    at wrapper.qx.tool.cli.commands.Compile.prototype.createMakersFromConfig() [as createMakersFromConfig] (C:\_vza\@repos\github.windows\qooxdoo\qooxdoo-compiler\source\class\qx\tool\cli\commands\Compile.js:633:21)
    at async wrapper.qx.tool.cli.commands.Compile.prototype._loadConfigAndStartMaking() [as _loadConfigAndStartMaking] (C:\_vza\@repos\github.windows\qooxdoo\qooxdoo-compiler\source\class\qx\tool\cli\commands\Compile.js:378:36)
    at async wrapper.qx.tool.cli.commands.Compile.prototype.process() [as process] (C:\_vza\@repos\github.windows\qooxdoo\qooxdoo-compiler\source\class\qx\tool\cli\commands\Compile.js:344:7)
    at async wrapper.qx.tool.cli.commands.Deploy.prototype.process() [as process] (C:\_vza\@repos\github.windows\qooxdoo\qooxdoo-compiler\source\class\qx\tool\cli\commands\Deploy.js:118:7)
    at async wrapper.qx.tool.cli.Cli.prototype.processCommand() [as processCommand] (C:\_vza\@repos\github.windows\qooxdoo\qooxdoo-compiler\source\class\qx\tool\cli\Cli.js:202:16)
```

**Comment by hkollmann** [comment]
Done with #695
