### ISSUE TITLE
Error about `TypeScriptWriter-base-declaration.txt` occurs when compile with `--typescript`

### ISSUE THREAD

**Issue by konichan7** [qooxdoo/qooxdoo-compiler#819]
Full error like below.

```
Error: Error: ENOENT: no such file or directory, open 'C:\myWorkingDir\node_modules\@qooxdoo\compiler\lib\compiler\TypeScriptWriter-base_declaration.txt'
    at Promise.longStackTracesCaptureStackTrace [as _captureStackTrace] (C:\myWorkingDir\node_modules\@qooxdoo\compiler\lib\compiler\index.js:27354:29)
    at doThenable (C:\myWorkingDir\node_modules\@qooxdoo\compiler\lib\compiler\index.js:31349:23)
    at tryConvertToPromise (C:\myWorkingDir\node_modules\@qooxdoo\compiler\lib\compiler\index.js:31314:26)
    at PromiseArray._iterate (C:\myWorkingDir\node_modules\@qooxdoo\compiler\lib\compiler\index.js:30080:36)
    at PromiseArray.init [as _init] (C:\myWorkingDir\node_modules\@qooxdoo\compiler\lib\compiler\index.js:30068:20)
    at new PromiseArray (C:\myWorkingDir\node_modules\@qooxdoo\compiler\lib\compiler\index.js:30013:20)
    at Function.Promise.all (C:\myWorkingDir\node_modules\@qooxdoo\compiler\lib\compiler\index.js:29268:22)
    at Function.qx.Promise.__P_64_8() [as __P_64_8] (C:\myWorkingDir\node_modules\@qooxdoo\compiler\lib\compiler\index.js:26101:68)
    at Function.qx.Promise.all() [as all] (C:\myWorkingDir\node_modules\@qooxdoo\compiler\lib\compiler\index.js:25686:27)
    at wrapper.qx.tool.cli.commands.Compile.prototype._loadConfigAndStartMaking() [as _loadConfigAndStartMaking] (C:\myWorkingDir\node_modules\@qooxdoo\compiler\lib\compiler\index.js:51357:26)
    at async wrapper.qx.tool.cli.commands.Compile.prototype.process() [as process] (C:\myWorkingDir\node_modules\@qooxdoo\compiler\lib\compiler\index.js:51312:9)
    at async wrapper.qx.tool.cli.Cli.prototype.processCommand() [as processCommand] (C:\myWorkingDir\node_modules\@qooxdoo\compiler\lib\compiler\index.js:40530:18)
```

i fixed this problem by make new `TypeScriptWriter-base_declaration.txt` file with **dummy text** and locate it under that path (`node_modules\@qooxdoo\compiler\lib\compiler\`). but i'm still not sure this is the best option.

thanks.

**Comment by derrell** [comment]
This is a duplicate of #741. As a workaround right now, the error can be ignored as it causes no problems for the generated code. It is highly annoying, however.

**Comment by derrell** [comment]
Actually, maybe it isn't a duplicate, but appears related. The error message isn't quite the same, and the cause seems related.

**Comment by hkollmann** [comment]
This is solved in https://github.com/qooxdoo/qooxdoo/pull/10214. Should be backported.

**Comment by konichan7** [comment]
cool. 😊
